name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install emacs
      run: sudo apt-get install emacs
    - name: launch emacs
      run: |
        # Load my config
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "ls ./dotfiles"
        ls ./dotfiles       
        source ./dotfiles/.bashrc
        # Start daemon
        emi
        # Create terminal session
        emcnw
        # Create gui session
        emc
