name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install emacs
      run: sudo apt-get install emacs
#    - name: load my config
#      run: source .bashrc
    - name: start daemon
      run:  emacs --daemon
#    - name: launch terminal emacs
#      run: emacsclient -n -c -a -nw \"\";
    - name: launch gui emacs
      run: emacsclient -n -c -a \"\";
    - name: kill emacs
      run: emacsclient -e '(kill-emacs)'
